In [44]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from warnings import filterwarnings
#from mpl_toolkits.mplot3d import Axes3D
import statsmodels.api as sm
#import missingno as msno
#import statsmodels.stats.api as sms
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.neighbors import LocalOutlierFactor
#from scipy.stats import levene
#from scipy.stats import shapiro
#from scipy.stats.stats import pearsonr
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.preprocessing import scale
from sklearn.model_selection import ShuffleSplit, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.svm import SVC 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import ElasticNetCV
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
import xgboost as xgb
from xgboost import XGBRegressor, XGBClassifier
from lightgbm import LGBMRegressor, LGBMClassifier
from catboost import CatBoostRegressor, CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import tree
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_auc_score, roc_curve
#from yellowbrick.cluster import KElbowVisualizer
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.manifold import Isomap,TSNE
from sklearn.feature_selection import mutual_info_classif
#from tqdm.notebook import tqdm
from scipy.stats import ttest_ind
#import plotly.express as px
#import plotly.graph_objs as go
#import plotly.offline as pyo
#import scipy.stats as stats
#import pymc3 as pm
#from dataprep.eda import *
##from dataprep.eda import plot
###from dataprep.eda import plot_diff
#from dataprep.eda import plot_correlation
#from dataprep.eda import plot_missing
#import plotly.figure_factory as ff
#from collections import Counter
#import pandas_profiling as pp
#from mpl_toolkits.basemap import Basemap
import datetime as dt
#import plotly.express as px
#import plotly.graph_objects as go

filterwarnings("ignore", category=DeprecationWarning) 
filterwarnings("ignore", category=FutureWarning) 
filterwarnings("ignore", category=UserWarning)

In [45]:
GENOM_GENETICS = pd.read_csv("train.csv")
Data = GENOM_GENETICS.copy()

In [46]:
Data

,Patient Id,Patient Age,Genes in mother's side,Inherited from father,Maternal gene,Paternal gene,Blood cell count (mcL),Patient First Name,Family Name,Father's name,...,Birth defects,White Blood cell count (thousand per microliter),Blood test result,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Genetic Disorder,Disorder Subclass
0,PID0x6418,2.0,Yes,No,Yes,No,4.760603,Richard,NaN,Larre,...,NaN,9.857562,NaN,1.0,1.0,1.0,1.0,1.0,Mitochondrial genetic inheritance disorders,Leber's hereditary optic neuropathy
1,PID0x25d5,4.0,Yes,Yes,No,No,4.910669,Mike,NaN,Brycen,...,Multiple,5.522560,normal,1.0,NaN,1.0,1.0,0.0,NaN,Cystic fibrosis
2,PID0x4a82,6.0,Yes,No,No,No,4.893297,Kimberly,NaN,Nashon,...,Singular,NaN,normal,0.0,1.0,1.0,1.0,1.0,Multifactorial genetic inheritance disorders,Diabetes
3,PID0x4ac8,12.0,Yes,No,Yes,No,4.705280,Jeffery,Hoelscher,Aayaan,...,Singular,7.919321,inconclusive,0.0,0.0,1.0,0.0,0.0,Mitochondrial genetic inheritance disorders,Leigh syndrome
4,PID0x1bf7,11.0,Yes,No,NaN,Yes,4.720703,Johanna,Stutzman,Suave,...,Multiple,4.098210,NaN,0.0,0.0,0.0,0.0,NaN,Multifactorial genetic inheritance disorders,Cancer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33100,PID0x5ef9,5.0,Yes,No,Yes,Yes,4.694978,Arthur,Davis,Ormond,...,NaN,12.000000,normal,0.0,1.0,1.0,NaN,0.0,Mitochondrial genetic inheritance disorders,Leigh syndrome
33101,PID0x5d15,10.0,Yes,No,No,Yes,4.941887,Thomas,NaN,Nevin,...,Singular,8.588510,abnormal,1.0,0.0,0.0,0.0,1.0,Mitochondrial genetic inheritance disorders,Mitochondrial myopathy
33102,PID0x5e59,6.0,No,No,NaN,Yes,4.815613,Tami,Didonato,Jaqua,...,Multiple,6.179693,abnormal,0.0,0.0,1.0,1.0,0.0,Mitochondrial genetic inheritance disorders,NaN
33103,PID0x9a7f,1.0,No,Yes,No,Yes,4.981268,Francis,Carter,Yugo,...,Multiple,11.136567,normal,1.0,0.0,0.0,1.0,0.0,Single-gene inheritance diseases,Tay-Sachs
33104,PID0x1ba3,5.0,No,Yes,Yes,No,4.698224,Elisabeth,Peale,Jissie,...,Multiple,8.568009,abnormal,0.0,1.0,1.0,1.0,0.0,Mitochondrial genetic inheritance disorders,Leigh syndrome

In [47]:
Data.drop(["Patient Id","Patient First Name","Family Name","Father's name","Location of Institute",
          "Institute Name","Test 1","Test 2","Test 3","Test 4","Test 5","Symptom 1","Symptom 2",
           "Symptom 3","Symptom 4","Symptom 5"],inplace=True,axis=1)

In [48]:
Data["Birth asphyxia"] = Data["Birth asphyxia"].replace("No record",np.NaN)
Data["Birth asphyxia"] = Data["Birth asphyxia"].replace("Not available",np.NaN)

Data["Autopsy shows birth defect (if applicable)"] = Data["Autopsy shows birth defect (if applicable)"].replace("None",np.NaN)
Data["Autopsy shows birth defect (if applicable)"] = Data["Autopsy shows birth defect (if applicable)"].replace("Not applicable",np.NaN)

Data["H/O radiation exposure (x-ray)"] = Data["H/O radiation exposure (x-ray)"].replace("Not applicable",np.NaN)
Data["H/O radiation exposure (x-ray)"] = Data["H/O radiation exposure (x-ray)"].replace("-",np.NaN)

Data["H/O substance abuse"] = Data["H/O substance abuse"].replace("Not applicable",np.NaN)
Data["H/O substance abuse"] = Data["H/O substance abuse"].replace("-",np.NaN)

In [49]:
Data.rename(columns={"Patient Age":"Patient_Age",
                    "Genes in mother's side":"Genes_Mother_Side",
                    "Paternal gene":"Paternal_Gene",
                    "Blood cell count (mcL)":"Blood_Cell_mcL",
                    "Mother's age":"Mother_Age",
                    "Father's age":"Father_Age",
                    "Respiratory Rate (breaths/min)":"Respiratory_Rate_Breaths_Min",
                    "Heart Rate (rates/min":"Heart_Rates_Min",
                    "Parental consent":"Parental_Consent",
                    "Follow-up":"Follow_Up",
                    "Birth asphyxia":"Birth_Asphyxia",
                    "Autopsy shows birth defect (if applicable)":"Autopsy_Birth_Defect",
                    "Place of birth":"Place_Birth",
                    "Folic acid details (peri-conceptional)":"Folic_Acid",
                    "H/O serious maternal illness":"Maternal_Illness",
                    "H/O radiation exposure (x-ray)":"Radiation_Exposure",
                    "H/O substance abuse":"Substance_Abuse",
                    "Assisted conception IVF/ART":"Assisted_Conception",
                    "History of anomalies in previous pregnancies":"History_Previous_Pregnancies",
                    "No. of previous abortion":"Previous_Abortion",
                    "Birth defects":"Birth_Defects",
                    "White Blood cell count (thousand per microliter)":"White_Blood_Cell",
                    "Blood test result":"Blood_Test_Result",
                    "Genetic Disorder":"Genetic_Disorder",
                    "Disorder Subclass":"Disorder_Subclass"},inplace=True)

In [50]:
Data.rename(columns={"Inherited from father":"Inherited_Father",
                    "Maternal gene":"Maternal_Gene"},inplace=True)

In [51]:
Data.sort_values(by=["Patient_Age"],inplace=True)

In [52]:
SAMPLE_ONE = Data[:1000]
SAMPLE_TWO = Data[4400:5600]
SAMPLE_THREE = Data[3453:6000]
SAMPLE_FOUR = Data[10000:13000]

SAMPLE_ONE = SAMPLE_ONE.reset_index(drop=True)
SAMPLE_TWO = SAMPLE_TWO.reset_index(drop=True)
SAMPLE_THREE = SAMPLE_THREE.reset_index(drop=True)
SAMPLE_FOUR = SAMPLE_FOUR.reset_index(drop=True)

In [53]:
SAMPLE_ONE["Inherited_Father"].fillna(SAMPLE_ONE["Inherited_Father"].mode()[0], inplace=True)
SAMPLE_ONE["Maternal_Gene"].fillna(SAMPLE_ONE["Maternal_Gene"].mode()[0], inplace=True)
SAMPLE_ONE["Respiratory_Rate_Breaths_Min"].fillna(SAMPLE_ONE["Respiratory_Rate_Breaths_Min"].mode()[0], inplace=True)
SAMPLE_ONE["Heart_Rates_Min"].fillna(SAMPLE_ONE["Heart_Rates_Min"].mode()[0], inplace=True)
SAMPLE_ONE["Follow_Up"].fillna(SAMPLE_ONE["Follow_Up"].mode()[0], inplace=True)
SAMPLE_ONE["Gender"].fillna(SAMPLE_ONE["Gender"].mode()[0], inplace=True)
SAMPLE_ONE["Birth_Asphyxia"].fillna(SAMPLE_ONE["Birth_Asphyxia"].mode()[0], inplace=True)
SAMPLE_ONE["Autopsy_Birth_Defect"].fillna(SAMPLE_ONE["Autopsy_Birth_Defect"].mode()[0], inplace=True)
SAMPLE_ONE["Place_Birth"].fillna(SAMPLE_ONE["Place_Birth"].mode()[0], inplace=True)
SAMPLE_ONE["Folic_Acid"].fillna(SAMPLE_ONE["Folic_Acid"].mode()[0], inplace=True)
SAMPLE_ONE["Maternal_Illness"].fillna(SAMPLE_ONE["Maternal_Illness"].mode()[0], inplace=True)
SAMPLE_ONE["Radiation_Exposure"].fillna(SAMPLE_ONE["Radiation_Exposure"].mode()[0], inplace=True)
SAMPLE_ONE["Substance_Abuse"].fillna(SAMPLE_ONE["Substance_Abuse"].mode()[0], inplace=True)
SAMPLE_ONE["Assisted_Conception"].fillna(SAMPLE_ONE["Assisted_Conception"].mode()[0], inplace=True)
SAMPLE_ONE["History_Previous_Pregnancies"].fillna(SAMPLE_ONE["History_Previous_Pregnancies"].mode()[0], inplace=True)
SAMPLE_ONE["Birth_Defects"].fillna(SAMPLE_ONE["Birth_Defects"].mode()[0], inplace=True)
SAMPLE_ONE["Blood_Test_Result"].fillna(SAMPLE_ONE["Blood_Test_Result"].mode()[0], inplace=True)


SAMPLE_ONE["Mother_Age"].fillna(SAMPLE_ONE.groupby(["Disorder_Subclass"])["Mother_Age"].transform("mean"),inplace=True)
SAMPLE_ONE["Father_Age"].fillna(SAMPLE_ONE.groupby(["Disorder_Subclass"])["Father_Age"].transform("mean"),inplace=True)
SAMPLE_ONE["Previous_Abortion"].fillna(SAMPLE_ONE.groupby(["Disorder_Subclass"])["Previous_Abortion"].transform("mean"),inplace=True)
SAMPLE_ONE["White_Blood_Cell"].fillna(SAMPLE_ONE.groupby(["Disorder_Subclass"])["White_Blood_Cell"].transform("mean"),inplace=True)

SAMPLE_ONE.dropna(inplace=True,axis=0)

SAMPLE_TWO["Inherited_Father"].fillna(SAMPLE_TWO["Inherited_Father"].mode()[0], inplace=True)
SAMPLE_TWO["Maternal_Gene"].fillna(SAMPLE_TWO["Maternal_Gene"].mode()[0], inplace=True)
SAMPLE_TWO["Respiratory_Rate_Breaths_Min"].fillna(SAMPLE_TWO["Respiratory_Rate_Breaths_Min"].mode()[0], inplace=True)
SAMPLE_TWO["Heart_Rates_Min"].fillna(SAMPLE_TWO["Heart_Rates_Min"].mode()[0], inplace=True)
SAMPLE_TWO["Follow_Up"].fillna(SAMPLE_TWO["Follow_Up"].mode()[0], inplace=True)
SAMPLE_TWO["Gender"].fillna(SAMPLE_TWO["Gender"].mode()[0], inplace=True)
SAMPLE_TWO["Birth_Asphyxia"].fillna(SAMPLE_TWO["Birth_Asphyxia"].mode()[0], inplace=True)
SAMPLE_TWO["Autopsy_Birth_Defect"].fillna(SAMPLE_TWO["Autopsy_Birth_Defect"].mode()[0], inplace=True)
SAMPLE_TWO["Place_Birth"].fillna(SAMPLE_TWO["Place_Birth"].mode()[0], inplace=True)
SAMPLE_TWO["Folic_Acid"].fillna(SAMPLE_TWO["Folic_Acid"].mode()[0], inplace=True)
SAMPLE_TWO["Maternal_Illness"].fillna(SAMPLE_TWO["Maternal_Illness"].mode()[0], inplace=True)
SAMPLE_TWO["Radiation_Exposure"].fillna(SAMPLE_TWO["Radiation_Exposure"].mode()[0], inplace=True)
SAMPLE_TWO["Substance_Abuse"].fillna(SAMPLE_TWO["Substance_Abuse"].mode()[0], inplace=True)
SAMPLE_TWO["Assisted_Conception"].fillna(SAMPLE_TWO["Assisted_Conception"].mode()[0], inplace=True)
SAMPLE_TWO["History_Previous_Pregnancies"].fillna(SAMPLE_TWO["History_Previous_Pregnancies"].mode()[0], inplace=True)
SAMPLE_TWO["Birth_Defects"].fillna(SAMPLE_TWO["Birth_Defects"].mode()[0], inplace=True)
SAMPLE_TWO["Blood_Test_Result"].fillna(SAMPLE_TWO["Blood_Test_Result"].mode()[0], inplace=True)


SAMPLE_TWO["Mother_Age"].fillna(SAMPLE_TWO.groupby(["Disorder_Subclass"])["Mother_Age"].transform("mean"),inplace=True)
SAMPLE_TWO["Father_Age"].fillna(SAMPLE_TWO.groupby(["Disorder_Subclass"])["Father_Age"].transform("mean"),inplace=True)
SAMPLE_TWO["Previous_Abortion"].fillna(SAMPLE_TWO.groupby(["Disorder_Subclass"])["Previous_Abortion"].transform("mean"),inplace=True)
SAMPLE_TWO["White_Blood_Cell"].fillna(SAMPLE_TWO.groupby(["Disorder_Subclass"])["White_Blood_Cell"].transform("mean"),inplace=True)

SAMPLE_TWO.dropna(inplace=True,axis=0)


SAMPLE_THREE["Inherited_Father"].fillna(SAMPLE_THREE["Inherited_Father"].mode()[0], inplace=True)
SAMPLE_THREE["Maternal_Gene"].fillna(SAMPLE_THREE["Maternal_Gene"].mode()[0], inplace=True)
SAMPLE_THREE["Respiratory_Rate_Breaths_Min"].fillna(SAMPLE_THREE["Respiratory_Rate_Breaths_Min"].mode()[0], inplace=True)
SAMPLE_THREE["Heart_Rates_Min"].fillna(SAMPLE_THREE["Heart_Rates_Min"].mode()[0], inplace=True)
SAMPLE_THREE["Follow_Up"].fillna(SAMPLE_THREE["Follow_Up"].mode()[0], inplace=True)
SAMPLE_THREE["Gender"].fillna(SAMPLE_THREE["Gender"].mode()[0], inplace=True)
SAMPLE_THREE["Birth_Asphyxia"].fillna(SAMPLE_THREE["Birth_Asphyxia"].mode()[0], inplace=True)
SAMPLE_THREE["Autopsy_Birth_Defect"].fillna(SAMPLE_THREE["Autopsy_Birth_Defect"].mode()[0], inplace=True)
SAMPLE_THREE["Place_Birth"].fillna(SAMPLE_THREE["Place_Birth"].mode()[0], inplace=True)
SAMPLE_THREE["Folic_Acid"].fillna(SAMPLE_THREE["Folic_Acid"].mode()[0], inplace=True)
SAMPLE_THREE["Maternal_Illness"].fillna(SAMPLE_THREE["Maternal_Illness"].mode()[0], inplace=True)
SAMPLE_THREE["Radiation_Exposure"].fillna(SAMPLE_THREE["Radiation_Exposure"].mode()[0], inplace=True)
SAMPLE_THREE["Substance_Abuse"].fillna(SAMPLE_THREE["Substance_Abuse"].mode()[0], inplace=True)
SAMPLE_THREE["Assisted_Conception"].fillna(SAMPLE_THREE["Assisted_Conception"].mode()[0], inplace=True)
SAMPLE_THREE["History_Previous_Pregnancies"].fillna(SAMPLE_THREE["History_Previous_Pregnancies"].mode()[0], inplace=True)
SAMPLE_THREE["Birth_Defects"].fillna(SAMPLE_THREE["Birth_Defects"].mode()[0], inplace=True)
SAMPLE_THREE["Blood_Test_Result"].fillna(SAMPLE_THREE["Blood_Test_Result"].mode()[0], inplace=True)


SAMPLE_THREE["Mother_Age"].fillna(SAMPLE_THREE.groupby(["Disorder_Subclass"])["Mother_Age"].transform("mean"),inplace=True)
SAMPLE_THREE["Father_Age"].fillna(SAMPLE_THREE.groupby(["Disorder_Subclass"])["Father_Age"].transform("mean"),inplace=True)
SAMPLE_THREE["Previous_Abortion"].fillna(SAMPLE_THREE.groupby(["Disorder_Subclass"])["Previous_Abortion"].transform("mean"),inplace=True)
SAMPLE_THREE["White_Blood_Cell"].fillna(SAMPLE_THREE.groupby(["Disorder_Subclass"])["White_Blood_Cell"].transform("mean"),inplace=True)

SAMPLE_THREE.dropna(inplace=True,axis=0)

SAMPLE_FOUR["Inherited_Father"].fillna(SAMPLE_FOUR["Inherited_Father"].mode()[0], inplace=True)
SAMPLE_FOUR["Maternal_Gene"].fillna(SAMPLE_FOUR["Maternal_Gene"].mode()[0], inplace=True)
SAMPLE_FOUR["Respiratory_Rate_Breaths_Min"].fillna(SAMPLE_FOUR["Respiratory_Rate_Breaths_Min"].mode()[0], inplace=True)
SAMPLE_FOUR["Heart_Rates_Min"].fillna(SAMPLE_FOUR["Heart_Rates_Min"].mode()[0], inplace=True)
SAMPLE_FOUR["Follow_Up"].fillna(SAMPLE_FOUR["Follow_Up"].mode()[0], inplace=True)
SAMPLE_FOUR["Gender"].fillna(SAMPLE_FOUR["Gender"].mode()[0], inplace=True)
SAMPLE_FOUR["Birth_Asphyxia"].fillna(SAMPLE_FOUR["Birth_Asphyxia"].mode()[0], inplace=True)
SAMPLE_FOUR["Autopsy_Birth_Defect"].fillna(SAMPLE_FOUR["Autopsy_Birth_Defect"].mode()[0], inplace=True)
SAMPLE_FOUR["Place_Birth"].fillna(SAMPLE_FOUR["Place_Birth"].mode()[0], inplace=True)
SAMPLE_FOUR["Folic_Acid"].fillna(SAMPLE_FOUR["Folic_Acid"].mode()[0], inplace=True)
SAMPLE_FOUR["Maternal_Illness"].fillna(SAMPLE_FOUR["Maternal_Illness"].mode()[0], inplace=True)
SAMPLE_FOUR["Radiation_Exposure"].fillna(SAMPLE_FOUR["Radiation_Exposure"].mode()[0], inplace=True)
SAMPLE_FOUR["Substance_Abuse"].fillna(SAMPLE_FOUR["Substance_Abuse"].mode()[0], inplace=True)
SAMPLE_FOUR["Assisted_Conception"].fillna(SAMPLE_FOUR["Assisted_Conception"].mode()[0], inplace=True)
SAMPLE_FOUR["History_Previous_Pregnancies"].fillna(SAMPLE_FOUR["History_Previous_Pregnancies"].mode()[0], inplace=True)
SAMPLE_FOUR["Birth_Defects"].fillna(SAMPLE_FOUR["Birth_Defects"].mode()[0], inplace=True)
SAMPLE_FOUR["Blood_Test_Result"].fillna(SAMPLE_FOUR["Blood_Test_Result"].mode()[0], inplace=True)


SAMPLE_FOUR["Mother_Age"].fillna(SAMPLE_FOUR.groupby(["Disorder_Subclass"])["Mother_Age"].transform("mean"),inplace=True)
SAMPLE_FOUR["Father_Age"].fillna(SAMPLE_FOUR.groupby(["Disorder_Subclass"])["Father_Age"].transform("mean"),inplace=True)
SAMPLE_FOUR["Previous_Abortion"].fillna(SAMPLE_FOUR.groupby(["Disorder_Subclass"])["Previous_Abortion"].transform("mean"),inplace=True)
SAMPLE_FOUR["White_Blood_Cell"].fillna(SAMPLE_FOUR.groupby(["Disorder_Subclass"])["White_Blood_Cell"].transform("mean"),inplace=True)

SAMPLE_FOUR.dropna(inplace=True,axis=0)

In [54]:
print("NAN VALUES:\n")
print(SAMPLE_ONE.isna().sum())
print("\n")
print("NAN VALUES:\n")
print(SAMPLE_TWO.isna().sum())
print("\n")
print("NAN VALUES:\n")
print(SAMPLE_THREE.isna().sum())
print("\n")
print("NAN VALUES:\n")
print(SAMPLE_FOUR.isna().sum())
print("\n")

NAN VALUES:

Patient_Age                     0
Genes_Mother_Side               0
Inherited_Father                0
Maternal_Gene                   0
Paternal_Gene                   0
Blood_Cell_mcL                  0
Mother_Age                      0
Father_Age                      0
Status                          0
Respiratory_Rate_Breaths_Min    0
Heart_Rates_Min                 0
Parental_Consent                0
Follow_Up                       0
Gender                          0
Birth_Asphyxia                  0
Autopsy_Birth_Defect            0
Place_Birth                     0
Folic_Acid                      0
Maternal_Illness                0
Radiation_Exposure              0
Substance_Abuse                 0
Assisted_Conception             0
History_Previous_Pregnancies    0
Previous_Abortion               0
Birth_Defects                   0
White_Blood_Cell                0
Blood_Test_Result               0
Genetic_Disorder                0
Disorder_Subclass               0
dtype: int64


NAN VALUES:

Patient_Age                     0
Genes_Mother_Side               0
Inherited_Father                0
Maternal_Gene                   0
Paternal_Gene                   0
Blood_Cell_mcL                  0
Mother_Age                      0
Father_Age                      0
Status                          0
Respiratory_Rate_Breaths_Min    0
Heart_Rates_Min                 0
Parental_Consent                0
Follow_Up                       0
Gender                          0
Birth_Asphyxia                  0
Autopsy_Birth_Defect            0
Place_Birth                     0
Folic_Acid                      0
Maternal_Illness                0
Radiation_Exposure              0
Substance_Abuse                 0
Assisted_Conception             0
History_Previous_Pregnancies    0
Previous_Abortion               0
Birth_Defects                   0
White_Blood_Cell                0
Blood_Test_Result               0
Genetic_Disorder                0
Disorder_Subclass               0
dtype: int64


NAN VALUES:

Patient_Age                     0
Genes_Mother_Side               0
Inherited_Father                0
Maternal_Gene                   0
Paternal_Gene                   0
Blood_Cell_mcL                  0
Mother_Age                      0
Father_Age                      0
Status                          0
Respiratory_Rate_Breaths_Min    0
Heart_Rates_Min                 0
Parental_Consent                0
Follow_Up                       0
Gender                          0
Birth_Asphyxia                  0
Autopsy_Birth_Defect            0
Place_Birth                     0
Folic_Acid                      0
Maternal_Illness                0
Radiation_Exposure              0
Substance_Abuse                 0
Assisted_Conception             0
History_Previous_Pregnancies    0
Previous_Abortion               0
Birth_Defects                   0
White_Blood_Cell                0
Blood_Test_Result               0
Genetic_Disorder                0
Disorder_Subclass               0
dtype: int64


NAN VALUES:

Patient_Age                     0
Genes_Mother_Side               0
Inherited_Father                0
Maternal_Gene                   0
Paternal_Gene                   0
Blood_Cell_mcL                  0
Mother_Age                      0
Father_Age                      0
Status                          0
Respiratory_Rate_Breaths_Min    0
Heart_Rates_Min                 0
Parental_Consent                0
Follow_Up                       0
Gender                          0
Birth_Asphyxia                  0
Autopsy_Birth_Defect            0
Place_Birth                     0
Folic_Acid                      0
Maternal_Illness                0
Radiation_Exposure              0
Substance_Abuse                 0
Assisted_Conception             0
History_Previous_Pregnancies    0
Previous_Abortion               0
Birth_Defects                   0
White_Blood_Cell                0
Blood_Test_Result               0
Genetic_Disorder                0
Disorder_Subclass               0
dtype: int64

In [55]:
Pre_Two_Data = Data.copy()

In [56]:
Data.dropna(inplace=True,axis=0)

In [57]:
Data = Data.reset_index(drop=True)

In [58]:
print("NAN VALUES:\n")
print(Data.isna().sum())

NAN VALUES:

Patient_Age                     0
Genes_Mother_Side               0
Inherited_Father                0
Maternal_Gene                   0
Paternal_Gene                   0
Blood_Cell_mcL                  0
Mother_Age                      0
Father_Age                      0
Status                          0
Respiratory_Rate_Breaths_Min    0
Heart_Rates_Min                 0
Parental_Consent                0
Follow_Up                       0
Gender                          0
Birth_Asphyxia                  0
Autopsy_Birth_Defect            0
Place_Birth                     0
Folic_Acid                      0
Maternal_Illness                0
Radiation_Exposure              0
Substance_Abuse                 0
Assisted_Conception             0
History_Previous_Pregnancies    0
Previous_Abortion               0
Birth_Defects                   0
White_Blood_Cell                0
Blood_Test_Result               0
Genetic_Disorder                0
Disorder_Subclass               0
dtype: int64

In [59]:
Encode_Data = Data.copy()

Encode_Func = LabelEncoder()

Encode_Data["Genes_Mother_Side"] = Encode_Func.fit_transform(Encode_Data["Genes_Mother_Side"])
Encode_Data["Inherited_Father"] = Encode_Func.fit_transform(Encode_Data["Inherited_Father"])
Encode_Data["Maternal_Gene"] = Encode_Func.fit_transform(Encode_Data["Maternal_Gene"])
Encode_Data["Paternal_Gene"] = Encode_Func.fit_transform(Encode_Data["Paternal_Gene"])
Encode_Data["Status"] = Encode_Func.fit_transform(Encode_Data["Status"])
Encode_Data["Respiratory_Rate_Breaths_Min"] = Encode_Func.fit_transform(Encode_Data["Respiratory_Rate_Breaths_Min"])
Encode_Data["Heart_Rates_Min"] = Encode_Func.fit_transform(Encode_Data["Heart_Rates_Min"])
Encode_Data["Follow_Up"] = Encode_Func.fit_transform(Encode_Data["Follow_Up"])
Encode_Data["Gender"] = Encode_Func.fit_transform(Encode_Data["Gender"])
Encode_Data["Birth_Asphyxia"] = Encode_Func.fit_transform(Encode_Data["Birth_Asphyxia"])
Encode_Data["Autopsy_Birth_Defect"] = Encode_Func.fit_transform(Encode_Data["Autopsy_Birth_Defect"])
Encode_Data["Place_Birth"] = Encode_Func.fit_transform(Encode_Data["Place_Birth"])
Encode_Data["Folic_Acid"] = Encode_Func.fit_transform(Encode_Data["Folic_Acid"])
Encode_Data["Maternal_Illness"] = Encode_Func.fit_transform(Encode_Data["Maternal_Illness"])
Encode_Data["Radiation_Exposure"] = Encode_Func.fit_transform(Encode_Data["Radiation_Exposure"])
Encode_Data["Substance_Abuse"] = Encode_Func.fit_transform(Encode_Data["Substance_Abuse"])
Encode_Data["Assisted_Conception"] = Encode_Func.fit_transform(Encode_Data["Assisted_Conception"])
Encode_Data["History_Previous_Pregnancies"] = Encode_Func.fit_transform(Encode_Data["History_Previous_Pregnancies"])
Encode_Data["Birth_Defects"] = Encode_Func.fit_transform(Encode_Data["Birth_Defects"])
Encode_Data["Blood_Test_Result"] = Encode_Func.fit_transform(Encode_Data["Blood_Test_Result"])
Encode_Data["Genetic_Disorder"] = Encode_Func.fit_transform(Encode_Data["Genetic_Disorder"])
Encode_Data["Disorder_Subclass"] = Encode_Func.fit_transform(Encode_Data["Disorder_Subclass"])
Encode_Data["Parental_Consent"] = Encode_Func.fit_transform(Encode_Data["Parental_Consent"])

Encode_Data = Encode_Data.astype("float32")

In [60]:
Encode_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Patient_Age                   427 non-null    float32
 1   Genes_Mother_Side             427 non-null    float32
 2   Inherited_Father              427 non-null    float32
 3   Maternal_Gene                 427 non-null    float32
 4   Paternal_Gene                 427 non-null    float32
 5   Blood_Cell_mcL                427 non-null    float32
 6   Mother_Age                    427 non-null    float32
 7   Father_Age                    427 non-null    float32
 8   Status                        427 non-null    float32
 9   Respiratory_Rate_Breaths_Min  427 non-null    float32
 10  Heart_Rates_Min               427 non-null    float32
 11  Parental_Consent              427 non-null    float32
 12  Follow_Up                     427 non-null    float32
 13  Gender                        427 non-null    float32
 14  Birth_Asphyxia                427 non-null    float32
 15  Autopsy_Birth_Defect          427 non-null    float32
 16  Place_Birth                   427 non-null    float32
 17  Folic_Acid                    427 non-null    float32
 18  Maternal_Illness              427 non-null    float32
 19  Radiation_Exposure            427 non-null    float32
 20  Substance_Abuse               427 non-null    float32
 21  Assisted_Conception           427 non-null    float32
 22  History_Previous_Pregnancies  427 non-null    float32
 23  Previous_Abortion             427 non-null    float32
 24  Birth_Defects                 427 non-null    float32
 25  White_Blood_Cell              427 non-null    float32
 26  Blood_Test_Result             427 non-null    float32
 27  Genetic_Disorder              427 non-null    float32
 28  Disorder_Subclass             427 non-null    float32
dtypes: float32(29)
memory usage: 48.5 KB

In [61]:
Encode_Data

,Patient_Age,Genes_Mother_Side,Inherited_Father,Maternal_Gene,Paternal_Gene,Blood_Cell_mcL,Mother_Age,Father_Age,Status,Respiratory_Rate_Breaths_Min,...,Radiation_Exposure,Substance_Abuse,Assisted_Conception,History_Previous_Pregnancies,Previous_Abortion,Birth_Defects,White_Blood_Cell,Blood_Test_Result,Genetic_Disorder,Disorder_Subclass
0,0.0,0.0,0.0,1.0,0.0,5.032100,22.0,57.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,7.242334,0.0,0.0,4.0
1,0.0,1.0,0.0,0.0,1.0,4.699308,49.0,30.0,0.0,0.0,...,1.0,0.0,1.0,1.0,4.0,0.0,3.257910,2.0,0.0,6.0
2,0.0,1.0,1.0,1.0,0.0,5.020172,27.0,21.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.462522,2.0,0.0,5.0
3,0.0,1.0,1.0,0.0,1.0,5.301917,51.0,35.0,0.0,0.0,...,0.0,0.0,1.0,0.0,4.0,0.0,11.219541,3.0,1.0,2.0
4,0.0,0.0,1.0,0.0,0.0,4.720809,39.0,60.0,0.0,0.0,...,0.0,0.0,1.0,1.0,3.0,0.0,5.704165,1.0,2.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,14.0,0.0,1.0,1.0,0.0,4.497377,44.0,46.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,8.647761,2.0,0.0,5.0
423,14.0,1.0,0.0,0.0,0.0,4.925360,46.0,35.0,0.0,0.0,...,1.0,0.0,0.0,1.0,4.0,1.0,3.000000,0.0,0.0,5.0
424,14.0,0.0,0.0,0.0,0.0,5.118062,39.0,30.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,8.184196,2.0,2.0,7.0
425,14.0,1.0,0.0,1.0,0.0,5.096929,41.0,24.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,10.946406,3.0,2.0,3.0
426,14.0,0.0,0.0,0.0,0.0,4.818157,47.0,23.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,4.726898,2.0,2.0,7.0

In [62]:
Genetic_Disorder_Data = Encode_Data.drop("Disorder_Subclass",axis=1)

In [63]:
Disorder_Subclass_Data = Encode_Data.drop("Genetic_Disorder",axis=1)

In [64]:
Genetic_Disorder_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Patient_Age                   427 non-null    float32
 1   Genes_Mother_Side             427 non-null    float32
 2   Inherited_Father              427 non-null    float32
 3   Maternal_Gene                 427 non-null    float32
 4   Paternal_Gene                 427 non-null    float32
 5   Blood_Cell_mcL                427 non-null    float32
 6   Mother_Age                    427 non-null    float32
 7   Father_Age                    427 non-null    float32
 8   Status                        427 non-null    float32
 9   Respiratory_Rate_Breaths_Min  427 non-null    float32
 10  Heart_Rates_Min               427 non-null    float32
 11  Parental_Consent              427 non-null    float32
 12  Follow_Up                     427 non-null    float32
 13  Gender                        427 non-null    float32
 14  Birth_Asphyxia                427 non-null    float32
 15  Autopsy_Birth_Defect          427 non-null    float32
 16  Place_Birth                   427 non-null    float32
 17  Folic_Acid                    427 non-null    float32
 18  Maternal_Illness              427 non-null    float32
 19  Radiation_Exposure            427 non-null    float32
 20  Substance_Abuse               427 non-null    float32
 21  Assisted_Conception           427 non-null    float32
 22  History_Previous_Pregnancies  427 non-null    float32
 23  Previous_Abortion             427 non-null    float32
 24  Birth_Defects                 427 non-null    float32
 25  White_Blood_Cell              427 non-null    float32
 26  Blood_Test_Result             427 non-null    float32
 27  Genetic_Disorder              427 non-null    float32
dtypes: float32(28)
memory usage: 46.8 KB

In [65]:
Genetic_Disorder_Data

,Patient_Age,Genes_Mother_Side,Inherited_Father,Maternal_Gene,Paternal_Gene,Blood_Cell_mcL,Mother_Age,Father_Age,Status,Respiratory_Rate_Breaths_Min,...,Maternal_Illness,Radiation_Exposure,Substance_Abuse,Assisted_Conception,History_Previous_Pregnancies,Previous_Abortion,Birth_Defects,White_Blood_Cell,Blood_Test_Result,Genetic_Disorder
0,0.0,0.0,0.0,1.0,0.0,5.032100,22.0,57.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7.242334,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,4.699308,49.0,30.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,4.0,0.0,3.257910,2.0,0.0
2,0.0,1.0,1.0,1.0,0.0,5.020172,27.0,21.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.462522,2.0,0.0
3,0.0,1.0,1.0,0.0,1.0,5.301917,51.0,35.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,4.0,0.0,11.219541,3.0,1.0
4,0.0,0.0,1.0,0.0,0.0,4.720809,39.0,60.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,3.0,0.0,5.704165,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,14.0,0.0,1.0,1.0,0.0,4.497377,44.0,46.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,8.647761,2.0,0.0
423,14.0,1.0,0.0,0.0,0.0,4.925360,46.0,35.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,4.0,1.0,3.000000,0.0,0.0
424,14.0,0.0,0.0,0.0,0.0,5.118062,39.0,30.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.184196,2.0,2.0
425,14.0,1.0,0.0,1.0,0.0,5.096929,41.0,24.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,10.946406,3.0,2.0
426,14.0,0.0,0.0,0.0,0.0,4.818157,47.0,23.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,4.726898,2.0,2.0

In [66]:
Disorder_Subclass_Data

,Patient_Age,Genes_Mother_Side,Inherited_Father,Maternal_Gene,Paternal_Gene,Blood_Cell_mcL,Mother_Age,Father_Age,Status,Respiratory_Rate_Breaths_Min,...,Maternal_Illness,Radiation_Exposure,Substance_Abuse,Assisted_Conception,History_Previous_Pregnancies,Previous_Abortion,Birth_Defects,White_Blood_Cell,Blood_Test_Result,Disorder_Subclass
0,0.0,0.0,0.0,1.0,0.0,5.032100,22.0,57.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7.242334,0.0,4.0
1,0.0,1.0,0.0,0.0,1.0,4.699308,49.0,30.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,4.0,0.0,3.257910,2.0,6.0
2,0.0,1.0,1.0,1.0,0.0,5.020172,27.0,21.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.462522,2.0,5.0
3,0.0,1.0,1.0,0.0,1.0,5.301917,51.0,35.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,4.0,0.0,11.219541,3.0,2.0
4,0.0,0.0,1.0,0.0,0.0,4.720809,39.0,60.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,3.0,0.0,5.704165,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,14.0,0.0,1.0,1.0,0.0,4.497377,44.0,46.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,8.647761,2.0,5.0
423,14.0,1.0,0.0,0.0,0.0,4.925360,46.0,35.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,4.0,1.0,3.000000,0.0,5.0
424,14.0,0.0,0.0,0.0,0.0,5.118062,39.0,30.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.184196,2.0,7.0
425,14.0,1.0,0.0,1.0,0.0,5.096929,41.0,24.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,10.946406,3.0,3.0
426,14.0,0.0,0.0,0.0,0.0,4.818157,47.0,23.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,4.726898,2.0,7.0

In [67]:
Disorder_Subclass_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Patient_Age                   427 non-null    float32
 1   Genes_Mother_Side             427 non-null    float32
 2   Inherited_Father              427 non-null    float32
 3   Maternal_Gene                 427 non-null    float32
 4   Paternal_Gene                 427 non-null    float32
 5   Blood_Cell_mcL                427 non-null    float32
 6   Mother_Age                    427 non-null    float32
 7   Father_Age                    427 non-null    float32
 8   Status                        427 non-null    float32
 9   Respiratory_Rate_Breaths_Min  427 non-null    float32
 10  Heart_Rates_Min               427 non-null    float32
 11  Parental_Consent              427 non-null    float32
 12  Follow_Up                     427 non-null    float32
 13  Gender                        427 non-null    float32
 14  Birth_Asphyxia                427 non-null    float32
 15  Autopsy_Birth_Defect          427 non-null    float32
 16  Place_Birth                   427 non-null    float32
 17  Folic_Acid                    427 non-null    float32
 18  Maternal_Illness              427 non-null    float32
 19  Radiation_Exposure            427 non-null    float32
 20  Substance_Abuse               427 non-null    float32
 21  Assisted_Conception           427 non-null    float32
 22  History_Previous_Pregnancies  427 non-null    float32
 23  Previous_Abortion             427 non-null    float32
 24  Birth_Defects                 427 non-null    float32
 25  White_Blood_Cell              427 non-null    float32
 26  Blood_Test_Result             427 non-null    float32
 27  Disorder_Subclass             427 non-null    float32
dtypes: float32(28)
memory usage: 46.8 KB

In [68]:
GENETIC_X =  Genetic_Disorder_Data.drop("Genetic_Disorder",axis=1)
GENETIC_Y = Genetic_Disorder_Data["Genetic_Disorder"]

In [69]:
GX_Train,GX_Test,GY_Train,GY_Test = train_test_split(GENETIC_X,GENETIC_Y,test_size=0.2,random_state=42,shuffle=True)

In [70]:
print("X TRAIN SHAPE: ",GX_Train.shape)
print("X TEST SHAPE: ",GX_Test.shape)
print("Y TRAIN SHAPE: ",GY_Train.shape)
print("Y TEST SHAPE: ",GY_Test.shape)

X TRAIN SHAPE:  (341, 27)
X TEST SHAPE:  (86, 27)
Y TRAIN SHAPE:  (341,)
Y TEST SHAPE:  (86,)

In [71]:
Scaler_Function = StandardScaler()

GX_Train = Scaler_Function.fit_transform(GX_Train)
GX_Test = Scaler_Function.fit_transform(GX_Test)

In [72]:
GX_Train[0:1]

array([[-1.3902324 ,  0.8652849 , -0.89148015, -1.0954452 , -0.8861943 ,
        -0.61514777,  0.5994946 , -0.1547194 ,  0.        , -0.9854432 ,
         0.8756937 ,  0.        , -0.8861943 ,  0.03992168,  1.0511603 ,
         0.9021251 ,  0.8861943 , -0.9854432 , -0.95693797,  0.97394633,
         1.0825777 , -1.0207429 ,  0.8601139 , -0.66065025,  0.91287094,
        -0.29096055,  1.2936949 ]], dtype=float32)

In [73]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, Flatten, LSTM,SimpleRNN
from tensorflow.keras.utils import to_categorical

In [74]:
GY_Train_cat = to_categorical(GY_Train)

In [75]:
input_shape = GX_Train.shape[1:]

In [76]:
import numpy as np

# Reshape for training and testing data
GX_Train_reshaped = GX_Train.reshape((GX_Train.shape[0], 1, GX_Train.shape[1]))
GX_Test_reshaped = GX_Test.reshape((GX_Test.shape[0], 1, GX_Test.shape[1]))

In [77]:
# 1. Multi-Layer Perceptron (MLP)
mlp = Sequential([
    Dense(128, activation='relu', input_shape=input_shape),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(GY_Train_cat.shape[1], activation='softmax')
])
mlp.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
mlp.fit(GX_Train, GY_Train_cat, epochs=10, verbose=1)

#  2. Convolutional Neural Network (CNN)
# cnn = Sequential([
#     Conv1D(32, kernel_size=3, activation='relu', input_shape=input_shape),
#     Flatten(),
#     Dense(64, activation='relu'),
#     Dense(GY_Train_cat.shape[1], activation='softmax')
# ])
# cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# cnn.fit(GX_Train, GY_Train_cat, epochs=10, verbose=1)

# 3. Long Short-Term Memory (LSTM)
# lstm = Sequential([
#     LSTM(50, activation='tanh', input_shape=input_shape),
#     Dense(GY_Train_cat.shape[1], activation='softmax')
# ])
# lstm.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# lstm.fit(GX_Train, GY_Train_cat, epochs=10, verbose=1)

# 4. Gradient Boosted Neural Network (with MLP as a base model)
# Optional deep model for boosting
gb_nn = Sequential([
    Dense(64, activation='relu', input_shape=input_shape),
    Dropout(0.1),
    Dense(32, activation='relu'),
    Dense(GY_Train_cat.shape[1], activation='softmax')
])
gb_nn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
gb_nn.fit(GX_Train, GY_Train_cat, epochs=10, verbose=1)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3205 - loss: 1.1032
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4970 - loss: 0.9138
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5479 - loss: 0.8723
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6245 - loss: 0.8153
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6065 - loss: 0.7767
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6908 - loss: 0.7481
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6846 - loss: 0.7247
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7194 - loss: 0.6858
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7183 - loss: 0.6475
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7523 - loss: 0.6310
Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4049 - loss: 1.1783
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4707 - loss: 1.0200
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5233 - loss: 0.9621
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5671 - loss: 0.9182
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.8463
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6775 - loss: 0.7927
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6122 - loss: 0.8172
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6558 - loss: 0.7544
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6833 - loss: 0.7643
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6547 - loss: 0.7268

In [78]:
modelsc = [mlp, gb_nn]

# Fit the models
for model in modelsc:
    print(f"Training {model.name}")
    model.fit(GX_Train, GY_Train_cat, epochs=5, verbose=1)

Training sequential_2
Epoch 1/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8028 - loss: 0.5471
Epoch 2/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7693 - loss: 0.5823
Epoch 3/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8210 - loss: 0.5304
Epoch 4/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8149 - loss: 0.5531
Epoch 5/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8063 - loss: 0.4860
Training sequential_3
Epoch 1/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7107 - loss: 0.7176
Epoch 2/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7327 - loss: 0.6452
Epoch 3/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7309 - loss: 0.6451
Epoch 4/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7573 - loss: 0.6008
Epoch 5/5
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7535 - loss: 0.6188

In [79]:
import numpy as np
from sklearn.model_selection import KFold
from keras.utils import to_categorical

# Assuming GX_Test is a NumPy array and GY_Test is a Pandas Series or NumPy array
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, val_index in kf.split(GX_Test):
    # Use .iloc for Pandas Series or use standard indexing for NumPy arrays
    X_train, X_val = GX_Test[train_index], GX_Test[val_index]
    
    # If GY_Test is a Pandas Series
    if isinstance(GY_Test, pd.Series):
        y_train, y_val = GY_Test.iloc[train_index], GY_Test.iloc[val_index]
    else:
        # If GY_Test is a NumPy array
        y_train, y_val = GY_Test[train_index], GY_Test[val_index]

    # Fit the model on training data
    model.fit(X_train, to_categorical(y_train), epochs=5, verbose=0)

In [80]:
import pandas as pd
from sklearn.model_selection import KFold

# Convert NumPy arrays to Pandas DataFrames
GX_Test_df = pd.DataFrame(GX_Test)
GY_Test_df = pd.Series(GY_Test)  # Assuming GY_Test is 1D

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, val_index in kf.split(GX_Test_df):
    X_train, X_val = GX_Test_df.iloc[train_index], GX_Test_df.iloc[val_index]
    
    # Use .iloc[] for GY_Test if it's a Series
    y_train, y_val = GY_Test_df.iloc[train_index], GY_Test_df.iloc[val_index]

    # Fit the model on training data
    model.fit(X_train, to_categorical(y_train), epochs=5, verbose=0)

In [81]:
# Assuming you have your models defined
modelsc = {
    "MLP": mlp,    # Multilayer Perceptron
    #"GB Neural Network": gb_nn  # Gradient Boosting Neural Network
}

for name, model in modelsc.items():
    # Fit the model
    model.fit(X_train, to_categorical(y_train), epochs=5, verbose=0)

    # Predict
    predictions = model.predict(X_val)
    
    # Calculate accuracy and MSE
    accuracy = accuracy_score(y_val, np.argmax(predictions, axis=1))
    mse = mean_squared_error(y_val, np.argmax(predictions, axis=1))

    # Print model performance
    print(f"{name}: ")
    print("----------")
    print("ACC -->", accuracy)
    print("MEAN SQUARED ERROR -->", mse)
    print("--------------z----------------")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
MLP:
----------
ACC --> 0.5882352941176471
MEAN SQUARED ERROR --> 1.4705882352941178
--------------z----------------